Update azure-hybrid-benefit-linux.md
Supported Versions:
The AHBforRhel extension currently supports:
RHEL 7
RHEL 8
 
Issue with RHEL 9 and Above- When attempting to use the AHB extension on RHEL 9 or later, the following error occurs:
ERROR: RHEL_BASE is not a valid license type
This happens because the AHB extension does not yet support RHEL 9 and therefore does not automatically install the RHUI client.
Workaround:
Until support is added for RHEL 9+, customers must manually configure the repositories after installing the extension.
Refer to the documented procedure here:
https://learn.microsoft.com/en-us/azure/virtual-machines/workloads/redhat/redhat-rhui#manual-update… 

Incident-679543218 Details - IcM